version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - keycloak

  postgres2:
    image: postgres:11
    volumes:
      - ./postgres_data2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - keycloak

  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
    depends_on:
      - postgres

  ldap-host:
    image: osixia/openldap:1.2.4
    environment:
      LDAP_ORGANISATION: tsh
      LDAP_DOMAIN: tsh.io
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
    volumes:
      - ./ldifs/example.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/example.ldif
    command: --copy-service

  vault:
    image: vault:1.2.1
    hostname: vault
    ports:
      - "8200:8200"
      - "8201:8201"
      - "8202:8202"
      - "8250:8250"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    depends_on:
      - keycloak
    command:
      - "server"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    restart: always
  networks:
    - keycloak: null
