version: '3.3'

services:

  terraform-shell:
    image: hashicorp/terraform
    container_name: terraform-shell
    volumes:
      - ./terraform:/playground
    working_dir: /playground
    entrypoint: /bin/ash
    tty: true
    depends_on:
      - keycloak
      - vault
    networks:
      - keycloak

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=root
      - KEYCLOAK_PASSWORD=root
    ports:
      - 8080:8080
    networks:
      - keycloak

  vault:
    image: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    networks:
      - keycloak

networks:
  keycloak: null
